Update map_handler.py
Resolved a small bug giving error as : 
" line 86, in _compute_best_seeker_action
    best_move = (next_cell[1] - seeker_pos[0], next_cell[0] - seeker_pos[1])
                 ~~~~~~~~~^^^
TypeError: 'GridNode' object is not subscriptable
ImportError: sys.meta_path is None, Python is likely shutting down "